name: flyway-mysql-rds

services:
  db:
    # Align with RDS MySQL version
    image: percona/percona-server:8.0.43
    container_name: flyway-db-local
    environment:
      MYSQL_ROOT_PASSWORD: "Welcome123"
    expose:
      - "3306"
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pWelcome123" ]
      interval: 5s
      timeout: 5s
      retries: 5

  db-migrations:
    image: flyway-mysql-rds:dev
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flyway-db-migrations-local
    restart: on-failure:8
    depends_on:
      db:
        condition: service_healthy
    environment:
      RDS_HOST: db
      SSL_MODE: REQUIRED
      FLYWAY_PASSWORD: "Welcome123"
    volumes:
      - ./sample/migrations:/flyway/sql
    command: migrate
