name: Create new RDS instance

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  create-rds:
    runs-on: ubuntu-latest

    steps:
      - name: Setup AWS CDK
        uses: ./.github/actions/cdk

      - name: Deploy RDS stack
        run: | 
          cd cdk && npx cdk deploy FlywayMySQLRDSStack --require-approval=never

