name: Destroy RDS instance

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  destroy-rds:
    runs-on: ubuntu-latest

    steps:
      - name: Setup AWS CDK
        uses: ./.github/actions/cdk

      - name: Destroy RDS stack
        run: | 
          cd cdk && npx cdk destroy FlywayMySQLRDSStack --require-approval=never

